# StockRadar Configuration Template

# Data Configuration
data:
  path: "data/market_data.csv"  # Data file path
  format: "csv"                 # Data format
  start_date: "2023-01-01"     # Start date
  end_date: "2023-12-31"       # End date

# Strategy Configuration
strategies:
  - name: "momentum_strategy"   # Strategy name
    module: "plugins.strategies.momentum"  # Strategy module path
    class: "MomentumStrategy"   # Strategy class name
    params:
      lookback_period: 20
      threshold: 0.05
    factors:
      - name: "returns"
        module: "plugins.factors.returns"
        class: "ReturnsFactor"
        params:
          period: 1
      - name: "volatility"
        module: "plugins.factors.volatility"
        class: "VolatilityFactor"
        params:
          window: 20

  - name: "mean_reversion_strategy"
    module: "plugins.strategies.mean_reversion"
    class: "MeanReversionStrategy"
    params:
      lookback_period: 60
      threshold: 2.0
    factors:
      - name: "zscore"
        module: "plugins.factors.zscore"
        class: "ZScoreFactor"
        params:
          window: 60

# Output Configuration
output:
  path: "output"
  format: "csv"
  save_metadata: true

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    collection_interval: 60  # seconds
  alerts:
    enabled: true
    log_level: "WARNING"
  lineage:
    enabled: true
    tracking_level: "detailed" 