# StockRadar Trading Configuration

# General Settings
general:
  mode: live #Changed from backtest to live
  log_level: INFO
  data_dir: data
  results_dir: results
  paper_trading: true
  debug: true

# Data Source Settings
data:
  provider: yfinance
  start_date: 2023-01-01
  end_date: 2024-01-01
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - META
  api_key: ""  # API key for data provider
  interval: 1m  # Using 1-minute intervals for more frequent updates
  universe_type: custom
  custom_universe: ["AAPL", "MSFT", "GOOGL"]  # Starting with a small universe for testing
  retry_count: 3
  retry_delay: 1
  timeout: 10

# Factor Settings
factors:
  ma_factor:
    enabled: true
    parameters:
      column: close
      windows: [5, 20, 50]
      ma_types: [sma, ema]
    
  volume_spike_factor:
    enabled: true
    parameters:
      window: 20
      threshold: 2.0

# Strategy Settings
strategies:
  # Moving Average Crossover Strategy
  - name: moving_average_crossover
    enabled: true
    parameters:
      short_window: 10
      long_window: 30
      position_size: 100
  # Mean Reversion Strategy
  - name: mean_reversion
    enabled: true
    parameters:
      lookback_period: 20
      entry_threshold: 2.0
      exit_threshold: 1.0
      position_size: 0.1
  # Momentum Breakout Strategy
  - name: MomentumBreakout
    enabled: false
    parameters:
      lookback_period: 20
      breakout_threshold: 0.02
      position_size: 1000
  # Golden Cross Strategy
  - name: GoldenCross
    enabled: false
    parameters:
      short_window: 50
      long_window: 200
      position_size: 1000

# Risk Management Settings
risk:
  max_position_size: 0.2
  max_drawdown: 0.1
  stop_loss: 0.05
  take_profit: 0.1
  max_positions: 10

# Portfolio Settings
portfolio:
  initial_capital: 100000
  commission: 0.001  # 0.1% commission per trade
  slippage: 0.001  # 0.1% slippage
  rebalance_frequency: daily
  max_positions: 10
  position_sizing: equal_weight

# Execution Settings
execution:
  provider: paper  # Using paper trading
  api_key: ""
  api_secret: ""
  paper_trading: true
  order_types:
    - market
    - limit
  default_order_type: market

# Backtesting Settings
backtesting:
  benchmark: SPY  # Benchmark symbol
  metrics:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - win_rate
    - profit_factor
  visualization:
    enabled: true
    save_plots: true
    plot_types:
      - equity_curve
      - drawdown
      - monthly_returns
      - trade_analysis
  initial_capital: 100000
  commission: 0.001
  slippage: 0.001

# Logging Settings
logging:
  level: INFO
  output_dir: output
  console_output: true
  file_output: true
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: stockradar.log
  max_size: 10485760  # 10MB
  backup_count: 5 